default_platform(:ios)

platform :ios do
  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    #docsPath = "docs/"
    podspecName = "Common.podspec"
    repoName = "CommonPodSpec"
    ensure_git_branch
    ensure_git_status_clean
    pod_lib_lint(allow_warnings: true)
    version = version_bump_podspec(path: podspecName, bump_type: type)
    #jazzy(module_version: version)
    git_add
    #git_commit(path: [docsPath, podspecName], message: "Release #{version}")
    git_commit(path: [podspecName], message: "Release #{version}")
    add_git_tag(tag: "#{version}")
    push_to_git_remote
    pod_push(allow_warnings: true, repo: repoName, verbose: true)
  end
end